### ISSUE TITLE
Audit all TODO and FIXME comments

### ISSUE THREAD

**Issue by vikramrajkumar** [bitshares/bitshares-2#29]
_From @vikramrajkumar on June 23, 2015 22:1_

_Copied from original issue: cryptonomex/graphene#77_

**Comment by oxarbitrage** [comment]
To get the ball rolling on this, i identified all the TODO in the bitshares core code and made a task list to give a further look to each of them so we all know where we are and keep track of them. No FIXME comments were found in the bitshares-core repo.


### App:

- [ ] https://github.com/bitshares/bitshares-core/blob/master/libraries/app/impacted.cpp#L33

- [ ] https://github.com/bitshares/bitshares-core/blob/master/libraries/app/database_api.cpp#L1774

- [ ] https://github.com/bitshares/bitshares-core/blob/master/libraries/app/application.cpp#L464
- [ ] https://github.com/bitshares/bitshares-core/blob/master/libraries/app/application.cpp#L543

### Chain:

- [ ] https://github.com/bitshares/bitshares-core/blob/master/libraries/chain/evaluator.cpp#L99

- [ ] https://github.com/bitshares/bitshares-core/blob/master/libraries/chain/db_init.cpp#L452

- [ ] https://github.com/bitshares/bitshares-core/blob/master/libraries/chain/proposal_evaluator.cpp#L54
- [ ] https://github.com/bitshares/bitshares-core/blob/master/libraries/chain/proposal_evaluator.cpp#L96

- [ ] https://github.com/bitshares/bitshares-core/blob/master/libraries/chain/db_block.cpp#L134
- [ ] https://github.com/bitshares/bitshares-core/blob/master/libraries/chain/db_block.cpp#L403
- [ ] https://github.com/bitshares/bitshares-core/blob/master/libraries/chain/db_block.cpp#L533

- [ ] https://github.com/bitshares/bitshares-core/blob/master/libraries/chain/vesting_balance_evaluator.cpp#L39
- [ ] https://github.com/bitshares/bitshares-core/blob/master/libraries/chain/vesting_balance_evaluator.cpp#L113
- [ ] https://github.com/bitshares/bitshares-core/blob/master/libraries/chain/vesting_balance_evaluator.cpp#L135

- [ ] https://github.com/bitshares/bitshares-core/blob/master/libraries/chain/db_update.cpp#L180

- [ ] https://github.com/bitshares/bitshares-core/blob/master/libraries/chain/buyback.cpp#L40

- [ ] https://github.com/bitshares/bitshares-core/blob/master/libraries/chain/db_market.cpp#L172

- [ ] https://github.com/bitshares/bitshares-core/blob/master/libraries/chain/db_management.cpp#L142

### Chain includes:

- [ ] https://github.com/bitshares/bitshares-core/blob/master/libraries/chain/include/graphene/chain/db_with.hpp#L66

- [ ] https://github.com/bitshares/bitshares-core/blob/master/libraries/chain/include/graphene/chain/account_object.hpp#L189


### Chain protocol:

- [ ] https://github.com/bitshares/bitshares-core/blob/master/libraries/chain/protocol/types.cpp#L44
- [ ] https://github.com/bitshares/bitshares-core/blob/master/libraries/chain/protocol/types.cpp#L48
- [ ] https://github.com/bitshares/bitshares-core/blob/master/libraries/chain/protocol/types.cpp#L67

- [ ] https://github.com/bitshares/bitshares-core/blob/master/libraries/chain/protocol/proposal.cpp#L32

- [ ] https://github.com/bitshares/bitshares-core/blob/master/libraries/chain/protocol/withdraw_permission.cpp#L57

### Chain protocol includes:

- [ ] https://github.com/bitshares/bitshares-core/blob/master/libraries/chain/include/graphene/chain/protocol/types.hpp#L259

- [ ] https://github.com/bitshares/bitshares-core/blob/master/libraries/chain/include/graphene/chain/protocol/committee_member.hpp#L94

### In tests:

- [ ] https://github.com/bitshares/bitshares-core/blob/master/tests/tests/operation_tests2.cpp#L463
- [ ] https://github.com/bitshares/bitshares-core/blob/master/tests/tests/operation_tests2.cpp#L1407
- [ ] https://github.com/bitshares/bitshares-core/blob/master/tests/tests/operation_tests2.cpp#L1430
- [ ] https://github.com/bitshares/bitshares-core/blob/master/tests/tests/operation_tests2.cpp#L1431
- [ ] https://github.com/bitshares/bitshares-core/blob/master/tests/tests/operation_tests2.cpp#L1456
- [ ] https://github.com/bitshares/bitshares-core/blob/master/tests/tests/operation_tests2.cpp#L1554
- [ ] https://github.com/bitshares/bitshares-core/blob/master/tests/tests/operation_tests2.cpp#L1653
- [ ] https://github.com/bitshares/bitshares-core/blob/master/tests/tests/operation_tests2.cpp#L1692

- [ ] https://github.com/bitshares/bitshares-core/blob/master/tests/tests/fee_tests.cpp#L727

- [ ] https://github.com/bitshares/bitshares-core/blob/master/tests/common/database_fixture.cpp#L266

- [ ] https://github.com/bitshares/bitshares-core/blob/master/tests/benchmarks/genesis_allocation.cpp#L96

- [ ] https://github.com/bitshares/bitshares-core/blob/master/tests/tests/operation_tests.cpp#L1815
- [ ] https://github.com/bitshares/bitshares-core/blob/master/tests/tests/operation_tests.cpp#L1818

- [ ] https://github.com/bitshares/bitshares-core/blob/master/tests/tests/authority_tests.cpp#L933
- [ ] https://github.com/bitshares/bitshares-core/blob/master/tests/tests/authority_tests.cpp#L1206
- [ ] https://github.com/bitshares/bitshares-core/blob/master/tests/tests/authority_tests.cpp#L1207
- [ ] https://github.com/bitshares/bitshares-core/blob/master/tests/tests/authority_tests.cpp#L1208
- [ ] https://github.com/bitshares/bitshares-core/blob/master/tests/tests/authority_tests.cpp#L1209

- [ ] https://github.com/bitshares/bitshares-core/blob/master/tests/tests/block_tests.cpp#L135
- [ ] https://github.com/bitshares/bitshares-core/blob/master/tests/tests/block_tests.cpp#L143

### Wallet:

- [ ] https://github.com/bitshares/bitshares-core/blob/master/libraries/wallet/wallet.cpp#L714
- [ ] https://github.com/bitshares/bitshares-core/blob/master/libraries/wallet/wallet.cpp#L931
- [ ] https://github.com/bitshares/bitshares-core/blob/master/libraries/wallet/wallet.cpp#L1056
- [ ] https://github.com/bitshares/bitshares-core/blob/master/libraries/wallet/wallet.cpp#L1121
- [ ] https://github.com/bitshares/bitshares-core/blob/master/libraries/wallet/wallet.cpp#L1517
- [ ] https://github.com/bitshares/bitshares-core/blob/master/libraries/wallet/wallet.cpp#L1815
- [ ] https://github.com/bitshares/bitshares-core/blob/master/libraries/wallet/wallet.cpp#L1820
- [ ] https://github.com/bitshares/bitshares-core/blob/master/libraries/wallet/wallet.cpp#L1893

### Wallet includes:

- [ ] https://github.com/bitshares/bitshares-core/blob/master/libraries/wallet/include/graphene/wallet/wallet.hpp#L631
- [ ] https://github.com/bitshares/bitshares-core/blob/master/libraries/wallet/include/graphene/wallet/wallet.hpp#L710
- [ ] https://github.com/bitshares/bitshares-core/blob/master/libraries/wallet/include/graphene/wallet/wallet.hpp#L874

### Wallet program:

- [ ] https://github.com/bitshares/bitshares-core/blob/master/programs/cli_wallet/main.cpp#L128
- [ ] https://github.com/bitshares/bitshares-core/blob/master/programs/cli_wallet/main.cpp#L178

### Egenesis:

- [ ] https://github.com/bitshares/bitshares-core/blob/master/libraries/egenesis/embed_genesis.cpp#L187

### Net:

- [ ] https://github.com/bitshares/bitshares-core/blob/master/libraries/net/node.cpp#L2375

### Others: 

- [ ] https://github.com/bitshares/bitshares-core/blob/master/programs/genesis_util/remove.py#L51
